# Production Database Connection Configuration
spring.datasource.url=jdbc:postgresql://dpg-d8f1mnog4nts738dvemg-a/vyg_75hy
spring.datasource.username=vyg_75hy_user
spring.datasource.password=gg4FTIPQn4ZQ7jTuzlTKW941oxqHGIZc
spring.datasource.driver-class-name=org.postgresql.Driver

# Production Optimisations
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate

# Production Security/Routing URL Mappings
app.frontend.url=${FRONTEND_URL:https://onrender.com}

# Diagnostic Filters for Render Logging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG
