# Local Development Profile
spring.datasource.url=jdbc:postgresql://localhost:5432/vyg
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.web=DEBUG

# Frontend URL for email links
app.frontend.url=http://localhost:3000
